export const users = [
    {
        id: 1,
        username: 'Tan Huynh',
        avatar: 'https://lh3.googleusercontent.com/ogw/ADea4I7wyN6WgGDhKr7mh08qsgwi0O2_3kg9d3XzCMuR=s32-c-mo',
        email: 'hntan2000@gmail.com',
        status: 'Kích hoạt',
    },
    {
        id: 2,
        username: 'Tan Huynh',
        avatar: 'https://lh3.googleusercontent.com/ogw/ADea4I7wyN6WgGDhKr7mh08qsgwi0O2_3kg9d3XzCMuR=s32-c-m',
        email: 'hntan2000@gmail.com',
        status: 'Kích hoạt',
    },
    {
        id: 3,
        username: 'Tan Huynh',
        avatar: 'https://lh3.googleusercontent.com/ogw/ADea4I7wyN6WgGDhKr7mh08qsgwi0O2_3kg9d3XzCMuR=s32-c-mo',
        email: 'hntan2000@gmail.com',
        status: 'Kích hoạt',
    },
    {
        id: 4,
        username: 'Tan Huynh',
        avatar: 'https://lh3.googleusercontent.com/ogw/ADea4I7wyN6WgGDhKr7mh08qsgwi0O2_3kg9d3XzCMuR=s32-c-mo',
        email: 'hntan2000@gmail.com',
        status: 'Kích hoạt',
    },
    {
        id: 5,
        username: 'Tan Huynh',
        avatar: 'https://lh3.googleusercontent.com/ogw/ADea4I7wyN6WgGDhKr7mh08qsgwi0O2_3kg9d3XzCMuR=s32-c-mo',
        email: 'hntan2000@gmail.com',
        status: 'Kích hoạt',
    },
    {
        id: 6,
        username: 'Tan Huynh',
        avatar: 'https://lh3.googleusercontent.com/ogw/ADea4I7wyN6WgGDhKr7mh08qsgwi0O2_3kg9d3XzCMuR=s32-c-mo',
        email: 'hntan2000@gmail.com',
        status: 'Kích hoạt',
    },
    {
        id: 7,
        username: 'Tan Huynh',
        avatar: 'https://lh3.googleusercontent.com/ogw/ADea4I7wyN6WgGDhKr7mh08qsgwi0O2_3kg9d3XzCMuR=s32-c-mo',
        email: 'hntan2000@gmail.com',
        status: 'Kích hoạt',
    },
    {
        id: 8,
        username: 'Tan Huynh',
        avatar: 'https://lh3.googleusercontent.com/ogw/ADea4I7wyN6WgGDhKr7mh08qsgwi0O2_3kg9d3XzCMuR=s32-c-mo',
        email: 'hntan2000@gmail.com',
        status: 'Kích hoạt',
    },
    {
        id: 9,
        username: 'Tan Huynh',
        avatar: 'https://lh3.googleusercontent.com/ogw/ADea4I7wyN6WgGDhKr7mh08qsgwi0O2_3kg9d3XzCMuR=s32-c-mo',
        email: 'hntan2000@gmail.com',
        status: 'Kích hoạt',
    },
    {
        id: 10,
        username: 'Tan Huynh',
        avatar: 'https://lh3.googleusercontent.com/ogw/ADea4I7wyN6WgGDhKr7mh08qsgwi0O2_3kg9d3XzCMuR=s32-c-mo',
        email: 'hntan2000@gmail.com',
        status: 'Kích hoạt',
    },
    {
        id: 11,
        username: 'Tan Huynh',
        avatar: 'https://lh3.googleusercontent.com/ogw/ADea4I7wyN6WgGDhKr7mh08qsgwi0O2_3kg9d3XzCMuR=s32-c-mo',
        email: 'hntan2000@gmail.com',
        status: 'Kích hoạt',
    },
    {
        id: 12,
        username: 'Tan Huynh',
        avatar: 'https://lh3.googleusercontent.com/ogw/ADea4I7wyN6WgGDhKr7mh08qsgwi0O2_3kg9d3XzCMuR=s32-c-mo',
        email: 'hntan2000@gmail.com',
        status: 'Kích hoạt',
    },
];

export const products = [
    {
        id: 1,
        name: 'Nhà giả kim',
        image: 'http://isach.info/images/story/cover/nha_gia_kim__paulo_coelho.jpg',
        stock: 123,
        status: 'Mở bán',
    },
    {
        id: 2,
        name: 'Nhà giả kim',
        image: 'http://isach.info/images/story/cover/nha_gia_kim__paulo_coelho.jpg',
        stock: 123,
        status: 'Mở bán',
    },
    {
        id: 3,
        name: 'Nhà giả kim',
        image: 'http://isach.info/images/story/cover/nha_gia_kim__paulo_coelho.jpg',
        stock: 123,
        status: 'Mở bán',
    },
    {
        id: 4,
        name: 'Nhà giả kim',
        image: 'http://isach.info/images/story/cover/nha_gia_kim__paulo_coelho.jpg',
        stock: 123,
        status: 'Mở bán',
    },
    {
        id: 5,
        name: 'Nhà giả kim',
        image: 'http://isach.info/images/story/cover/nha_gia_kim__paulo_coelho.jpg',
        stock: 123,
        status: 'Mở bán',
    },
    {
        id: 6,
        name: 'Nhà giả kim',
        image: 'http://isach.info/images/story/cover/nha_gia_kim__paulo_coelho.jpg',
        stock: 123,
        status: 'Mở bán',
    },
    {
        id: 7,
        name: 'Nhà giả kim',
        image: 'http://isach.info/images/story/cover/nha_gia_kim__paulo_coelho.jpg',
        stock: 123,
        status: 'Mở bán',
    },
    {
        id: 8,
        name: 'Nhà giả kim',
        image: 'http://isach.info/images/story/cover/nha_gia_kim__paulo_coelho.jpg',
        stock: 123,
        status: 'Mở bán',
    },
    {
        id: 9,
        name: 'Nhà giả kim',
        image: 'http://isach.info/images/story/cover/nha_gia_kim__paulo_coelho.jpg',
        stock: 123,
        status: 'Mở bán',
    },
    {
        id: 10,
        name: 'Nhà giả kim',
        image: 'http://isach.info/images/story/cover/nha_gia_kim__paulo_coelho.jpg',
        stock: 123,
        status: 'Mở bán',
    },
    {
        id: 11,
        name: 'Nhà giả kim',
        image: 'http://isach.info/images/story/cover/nha_gia_kim__paulo_coelho.jpg',
        stock: 123,
        status: 'Mở bán',
    },
    {
        id: 12,
        name: 'Nhà giả kim',
        image: 'http://isach.info/images/story/cover/nha_gia_kim__paulo_coelho.jpg',
        stock: 123,
        status: 'Mở bán',
    },
];
